export const APP_ROLES = {
  ADMIN: 'ADMIN',
  HR: 'HR',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE'
} as const;

export const ROLE_GROUPS = {
  ALL: [APP_ROLES.ADMIN, APP_ROLES.HR, APP_ROLES.MANAGER, APP_ROLES.EMPLOYEE],
  ADMIN_ONLY: [APP_ROLES.ADMIN],
  ADMIN_MANAGER: [APP_ROLES.ADMIN, APP_ROLES.MANAGER],
  ADMIN_MANAGER_EMPLOYEE: [APP_ROLES.ADMIN, APP_ROLES.MANAGER, APP_ROLES.EMPLOYEE],
  ADMIN_HR_MANAGER: [APP_ROLES.ADMIN, APP_ROLES.HR, APP_ROLES.MANAGER],
  HR_MANAGER_EMPLOYEE: [APP_ROLES.HR, APP_ROLES.MANAGER, APP_ROLES.EMPLOYEE]
} as const;

